### ISSUE TITLE
Next! 

### ISSUE THREAD

**Issue by vincentsarago** [RemotePixel/viewer.remotepixel.ca#3]
Version 2 of the viewer has been in production for more than a month now, and didn't get any user feedback ... so either it's really bad, either it's not 😄 

Here are some new feature I want to add:
- Allow multiple image selection (useful for sentinel-2) 
- re-design needed for☝️ to see what images are displayed
- update readme + doc
- add a share button ?

**Comment by steflhermitte** [comment]
Hi Vincent, 

Remote Pixel Viewer is absolutely a magnificent tool and I already thank you 1000x times! 

It might be a small detail but one option I would find handy is to allow the user to sort the resulting tiles in the bottom list (also) by date. Now when I click a blue tile in the polar regions, it often auto-selects multiple tiles. As a result, it requires some manual scrolling/searching in the bottom list to find the date you want as they are not ordered by date. Having a sort by date option would resolve this and would make it even handier.

Thanks and best regards,
Stef

**Comment by vincentsarago** [comment]
👋 Hi @steflhermitte,
First thanks for your comment, I'm very glad that you find the tool useful. 

> As a result, it requires some manual scrolling/searching in the bottom list to find the date you want as they are not ordered by date.

This is a bug, because it should! 
https://github.com/RemotePixel/viewer.remotepixel.ca/blob/a39b0c1dc3fc0f1e6d321a880e87daf164003790/js/app.js#L168

I couldn't reproduce this bug on Safari (which I usually use when developing the page) but this is definitely happening on Chrome. 

Gonna open a ticket and work on that ASAP. 

thanks @steflhermitte 🙏
