### ISSUE TITLE
index.html does't get properly loaded

### ISSUE THREAD

**Issue by rohitsharma0201** [RemotePixel/viewer.remotepixel.ca#8]
Hello Sir, When I tried to clone and run it on localhost but it didn't run properly.
Do I need to make any changes anywhere ? 
Like user id and password of aws or anything ?

**Comment by vincentsarago** [comment]
Hi @rohitsharma1415 
you need to edit `app.js` https://github.com/RemotePixel/viewer.remotepixel.ca/blob/master/js/app.js#L3-L7
and add 
- you mapbox token 
- your endpoint to landsat/cbers [remotepixel-tiler](https://github.com/RemotePixel/remotepixel-tiler) instances

**Comment by rohitsharma0201** [comment]
Sure Sir, Let me try once & Thank you for your Valuable response
